dist: trusty
language: rust
services: docker
sudo: required
python: 3.7
env:
  global:
  - CRATE_NAME=pwg
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-musl
  - env: TARGET=x86_64-apple-darwin
    os: osx
  - env: TARGET=x86_64-pc-windows-gnu
before_install:
- set -e
- rustup self update
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- bash ci/before_deploy.sh
deploy:
  api_key:
    secure: 64JhgeNJGJAyarFNcKIq9I/AZa5xmEFzx9tZyJ7xZov1I6JnA//QfmQOWEkcCyhVxVN4C6Vr3zvqKL2PuSscE1NZzb3nVWNkLfjtxyLJRB7MiTw7kussAyPxpTZPQkxmM8NiatLni/HLj0dpvSWWYv1QBEYusmP1ydOxg64RYjHI+zMmowPAgca4R2i69DUmpK0kUD8J+yjFag2LWZFg1zXc/o14vUo7Oebc/qrv212vn4jb2cadEk4T8JBlMMOP9E197EagJKYMVHgWSnxuqeZu7XaVT6V3Cs35A08x7dq6DQCiifNiFmM7ibHJGQutwuV7CcFEFb9PewFzSu/hNods+2jDvAZlOxR5El4aW0RK9EnFqVcdGJKXRRCtOo0wIw5mfhOUeM2heZdiHi8oV2Td7qNGnTHmyc2knDRNQjMOOCfD5EAopwVmLueDM1M7s9QjieyUEOGAVjBp4PJFwAh1un92U+HOaIU4EciCcfT9W/4NTplSo+tQbdSR4OPfzujdkedN0LMaxVQZ0h/QL1EDTCRZ7RAM9Gz7fW9DUKa9p8PbHKcP7TjAG/07BBIlWx4xWSDGQF8sTRruohjjRfYzoHxClCnUrPs+zW2NOxbr1vGplJWekDAOqvRouh6CCtlR03cIYNFpnqlAMskNsI0bN4g7RGRPjb+rUvnO5xg=
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
  provider: releases
  skip_cleanup: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_success: never
